security:
    user:
        password: password
spring:
    redis:
#       Configure for running Redis with Docker Toolbox.
        host: 192.168.99.100
#        password: secret
#        port: 6379
logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE        